### ISSUE TITLE
Bug in Tutorial 1

### ISSUE THREAD

**Issue by tzaffi** [scale-it/algorand-builder-tutorial#1]
Probably I should have created the issue here... I've created in the `algob` repo. Here is the issue:

https://github.com/scale-it/algo-builder/issues/516

**Comment by tzaffi** [comment]
I see now that the `part-1` branch has the correct `algod.config.js` with `alice` et. al. But this is still not correct in the actual tutorial.

**Comment by robert-zaremba** [comment]
Thanks for reporting. Didn't look here for a while.

**Comment by robert-zaremba** [comment]
This is already solved.
