### ISSUE TITLE
Import Statement Use Deprecated @algorand-builder/algob

### ISSUE THREAD

**Issue by sujithsomraaj** [scale-it/algorand-builder-tutorial#2]
`const { SignType, TransactionType, executeTransaction, balanceOf } = require('@algorand-builder/algob');`

In this line, https://github.com/scale-it/algorand-builder-tutorial/blob/part-1/scripts/0-gold.js#L1 please replace it with the new library

**Comment by rmeena840** [comment]
@sujithsomraaj This is done.
